version: "3"
services:
  mysql:
    container_name: skills_mysql
    build:
      context: ./
      dockerfile: build/mysql/Dockerfile.dev
    volumes:
      - mysql-data:/var/lib/mysql
      - ./build/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: skills
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      TZ: Asia/Tokyo
    ports:
      - 4306:3306
    networks:
      - default

  backend:
    container_name: skills_backend
    build:
      context: ./
      dockerfile: build/server/Dockerfile.dev
    volumes:
      # - node_modules:/code/node_modules # ローカルのvolumes
      - ./code:/code
      - /code/node_modules # マウントで消さないため
    ports:
      - 4000:4000
    working_dir: /code
    command: npm run dev
    depends_on:
      - mysql
    networks:
      - default

networks:
  default:
    external: false
volumes:
  mysql-data:
  # node_modules:
