version: "3"
services:
  mysql:
    container_name: skills_mysql
    build:
      context: ./
      dockerfile: mysql/Dockerfile.dev
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: skills
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      TZ: Asia/Tokyo
    ports:
      - 4306:4306
    networks:
      - dev-network

  backend:
    container_name: skills_backend
    build:
      context: ./
      dockerfile: build/Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules # マウントで消さないため(ローカルにマウントもさせない)
      - /app/.nuxt
      - /app/dist
    ports:
      - 8000:8000
    working_dir: /app
    command: yarn dev
    networks:
      - dev-network
    depends_on:
      - mysql

networks:
  dev-network:
    external: false # ここのコンテナのみで共有
volumes:
  mysql-data:
