# ######################
# 型定義
# ######################
type User {
  id: ID
  name: String
}
type Task {
  id: ID
  title: String
}
type Todo {
  id: ID
  title: String
}

# ######################
# Query
# ######################
type Query {
  users: [User]
  user(id: Int): User
  tasks: [Task]
  task(id: Int): Task
  todos: [Todo]
  todo(id: Int): Todo
}

# ######################
# Mutation
# ######################
type Mutation {
  createUser(name: String!): User
}
