extend type Query {
  index: [User]
  find(id: Int): User
}

extend type Mutation {
  login(input: LoginInput): User
  createUser(input: CreateUserInput!): CreateUserPayload!
  updateUser(id: Int!): User
  deleteUser(id: Int!): User
}

type User {
  id: ID!
  email: String
  password: String
  firstname: String
  lastname: String
  gender: Int
  birthday: String
  nearStation: String
  profile: String
}

"""
login
"""
input LoginInput {
  email: String!
  password: String!
}

"""
create
"""
input CreateUserInput {
  email: String
  password: String
  firstname: String
  lastname: String
  gender: Int
  birthday: String
  nearStation: String
  profile: String
}
type CreateUserPayload {
  user: User!
}
