type User {
  id: ID!
  name: String
  email: String
  password: String
}

extend type Query {
  users: [User]
  user(id: Int): User
}

extend type Mutation {
  createUser(name: String!): User
  updateUser(id: Int!): User
  deleteUser(id: Int!): User
}
