name: Deploy to Firebase Hosting # 任意

# pushをトリガー
on:
  push:
    branches: [master]
# stepの集まり, 並列実行(build, test, package, release, deployなど)
jobs:
  deploy: # 任意
    runs-on: ubuntu-latest # jobが実行される仮想環境
    steps:
      # [ユーザー名/リポジトリ名]のアクションを実行
      - name: Deploy Test
        uses: actions/checkout@v2
        run: npm run test
      # - name: Deploy Test 2
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
